### PR TITLE
Bugfix/remote exit codes

### PR DESCRIPTION
**Pull request by weipe**
I noticed that run_remote_script did not propagate the remote script's exit code, so that has been changed.

I also noted that when running in foreground mode, the command is executed with `tee` as the last process in the pipeline:
`command | tee logfile` which means that the final exit code of the process will be that of tee, which is basically always 0. I removed tee, to be able to get the exit code from the actual script.

I also added explicit instance configuration for termination on exit. I also changed to a cheaper instance type for running the test.

### CODE REVIEW

**Review by noreferences — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks good :)

But before we merge, could you sign <https://github.com/nimbo-sh/nimbo/blob/master/CLA.md>? Just add a new row with your identification. I've just added it, so you'll have to update your branch. We will also use these details to have a wall of people who have contributed.

**Comment by weipe** [comment]
Sorry, I just read the license file and realised I will not be able to use Nimbo as it is not open source. Our agency has an open source policy. Feel free to use my small changes if you like and good luck with the program!

**Comment by seuqaj114** [comment]
Thank you for your contribution.

While commits [ba019f9](https://github.com/nimbo-sh/nimbo/pull/2/commits/ba019f9b7ca32d181f723cd45aec0bf2c17f7fb8) and [cfab16a](https://github.com/nimbo-sh/nimbo/pull/2/commits/cfab16a9f25d748d64d6897580ac7f63bcf18f3c) are good to go, I cannot approve the change to the tee command.

The reason why we use tee is that it allows us to pipe the output to a file within the SSH command, while printing the output to the terminal as well. The proposed modification from this:
`full_command = f"{bash_cmd} {instance_id} {job_cmd} | tee {NIMBO_LOG}"`
to this:
`full_command = f"{bash_cmd} {instance_id} {job_cmd} >{NIMBO_LOG} 2>&1"`
prevents printing to the terminal when `run_on_background=False`, as all the output is being redirected to NIMBO_LOG.

Furthermore, currently the exit code of the bash script does not matter, since if the job fails within the instance, the bash script takes care of cleanup from inside the instance, and if the job fails in the python code prior to instance execution, the cleanup is done from outside the instance. 

If there is a different way to replace tee I would be happy to review it.

**Comment by seuqaj114** [comment]
Additionally, I would like to emphasize that for commercial purposes, this code is free to use and modify for up to 3 persons per AWS account. If you believe this is too restrictive, or you would like to see a different use case contemplated in the license, please do let us know.

**Comment by seuqaj114** [comment]
Closing as we changed the instance for testing and commit ba019f9 does not provide a clear advantage at this point.

**Pull request closed without merging**
